### ISSUE TITLE
How is reactive joins works?

### ISSUE THREAD

**Issue by hafeez1042** [yeputons/meteor-smart-publish#17]
First of all its a nice package for meteor. I have stucked on reactive join. Can you help me to write the code.

I have  one collection called cards.

``` javascript
Cards = new Mongo.Collection("cards")
```

it has a field called userId

I want to add a new field 'user' with all user profile fields. is it possible

**Comment by yeputons** [comment]
Hi @hafeez1042 !

This package does not alter ORM in any way - it handles publications only. To retrieve all user fields for a card you can write something like `Meteor.users.findOne(card.userId)`, which is boilerplate, of course.

<a href="http://stackoverflow.com/questions/15007231/whats-the-best-way-to-attach-behavior-to-a-meteor-collection">This</a> StackOverflow dicussion describes ways of attaching behavior or extra fields to items stored in collections. One option would be to add a `transform` function for your cards collection so `user` field is created during loading. It lacks reactivity, though, and I wouldn't recommend that: `transform` is not called reactively. If you're not very lucky, card may be loaded before corresponding user and there will be nothing to store in the `card.user` field, so this solution may even fail.

Another option that worths trying is to attach a _function_ instead of a property which will find corresponding user, that way you'll get all reactivity for free:

```
Cards = new Mongo.Collection("cards", {
  transform: function(card) {
    card.user = function() {
      return Meteor.users.findOne(card.userId);
    }
    return card;
  }
})

// ...
console.log(Cards.findOne("some_id").user().username);
```

Feel free to re-open the issue or just comment if you still have any doubts.

**Comment by hafeez1042** [comment]
That is great, but what does mean by "Reactive joins: just call this.addDependency and describe any join you want (details below)". I didn't  get it completely from Readme.

**Comment by yeputons** [comment]
@hafeez1042 oh, it's about reactive joins on server-side, for publications. Like, in SQL one can write `SELECT * FROM cards LEFT JOIN users on users.id = cards.user_id` and get both cards and all related users, you cannot do that in Mongo/Meteor as straightforward.

So, if you want to publish a subset of cards and all related users, but don't want to write boilerplate code that tracks dependencies between published cards and publish additional users - that's what the package does.
